In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('yellow2019_0.csv')

In [4]:
pd.read_csv('all1.csv')

,Unnamed: 0,Unnamed: 0.1,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,...,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,zone,zone_drop
0,381889,382200,2.0,2019-02-02 11:06:00,2019-02-02 11:09:11,3.0,0.00,1.0,N,11,...,2.50,0.0,0.5,0.00,0.0,0.3,3.30,0.0,brooklyn_1,brooklyn_1
1,471552,471863,1.0,2019-02-02 17:19:00,2019-02-02 17:19:09,1.0,0.00,1.0,N,11,...,2.50,0.0,0.5,0.00,0.0,0.3,3.30,0.0,brooklyn_1,brooklyn_1
2,606107,606421,1.0,2019-02-03 05:12:47,2019-02-03 05:13:09,1.0,0.00,5.0,N,11,...,55.00,0.0,0.0,0.00,0.0,0.3,55.30,0.0,brooklyn_1,brooklyn_1
3,684292,684606,1.0,2019-02-03 15:46:49,2019-02-03 15:48:03,1.0,0.00,5.0,N,11,...,47.00,0.0,0.0,9.45,0.0,0.3,56.75,0.0,brooklyn_1,brooklyn_1
4,706153,706467,2.0,2019-02-03 16:42:40,2019-02-03 16:56:10,1.0,1.89,1.0,N,11,...,10.50,0.0,0.5,0.00,0.0,0.3,11.30,0.0,brooklyn_1,brooklyn_1
5,746171,746486,2.0,2019-02-03 19:00:20,2019-02-03 19:10:59,1.0,1.35,1.0,N,11,...,8.50,0.0,0.5,0.00,0.0,0.3,9.30,0.0,brooklyn_1,brooklyn_1
6,884392,884711,2.0,2019-02-04 12:57:49,2019-02-04 13:06:47,1.0,1.37,1.0,N,11,...,7.50,0.0,0.5,0.00,0.0,0.3,8.30,0.0,brooklyn_1,brooklyn_1
7,888648,888967,2.0,2019-02-04 14:14:48,2019-02-04 14:15:01,6.0,0.07,1.0,N,11,...,2.50,0.0,0.5,0.00,0.0,0.3,3.30,0.0,brooklyn_1,brooklyn_1
8,2010441,2010778,2.0,2019-02-08 18:24:33,2019-02-08 18:24:53,1.0,0.00,1.0,N,11,...,2.50,1.0,0.5,0.00,0.0,0.3,4.30,0.0,brooklyn_1,brooklyn_1
9,2662020,2662384,2.0,2019-02-11 09:17:31,2019-02-11 09:24:20,1.0,1.30,1.0,N,11,...,7.00,0.0,0.5,0.00,0.0,0.3,7.80,0.0,brooklyn_1,brooklyn_1
10,2665624,2665988,1.0,2019-02-11 10:16:24,2019-02-11 10:19:05,1.0,19.40,1.0,N,11,...,3.50,0.0,0.5,0.00,0.0,0.3,4.30,0.0,brooklyn_1,brooklyn_1
11,2718189,2718553,2.0,2019-02-11 14:01:34,2019-02-11 14:11:42,2.0,1.72,1.0,N,11,...,9.00,0.0,0.5,0.00,0.0,0.3,9.80,0.0,brooklyn_1,brooklyn_1
12,2849879,2850257,1.0,2019-02-12 02:11:59,2019-02-12 02:14:18,1.0,0.50,1.0,N,11,...,4.00,3.0,0.5,0.00,0.0,0.3,7.80,2.5,brooklyn_1,brooklyn_1
13,3088803,3089194,2.0,2019-02-13 02:42:36,2019-02-13 02:42:40,2.0,0.00,1.0,N,11,...,2.50,0.5,0.5,0.00,0.0,0.3,3.80,0.0,brooklyn_1,brooklyn_1
14,3436910,3437317,2.0,2019-02-14 12:00:08,2019-02-14 12:06:17,1.0,1.02,1.0,N,11,...,6.00,0.0,0.5,0.00,0.0,0.3,6.80,0.0,brooklyn_1,brooklyn_1
15,122335,122641,2.0,2019-02-01 13:44:28,2019-02-01 13:59:03,1.0,1.69,1.0,N,21,...,11.00,0.0,0.5,0.00,0.0,0.3,11.80,0.0,brooklyn_1,brooklyn_1
16,2534118,2534476,2.0,2019-02-10 16:52:05,2019-02-10 16:58:23,3.0,1.44,1.0,N,21,...,7.00,0.0,0.5,1.95,0.0,0.3,9.75,0.0,brooklyn_1,brooklyn_1
17,2705444,2705808,2.0,2019-02-11 13:33:22,2019-02-11 13:43:43,2.0,1.23,1.0,N,21,...,8.50,0.0,0.5,0.00,0.0,0.3,9.30,0.0,brooklyn_1,brooklyn_1
18,2791152,2791528,2.0,2019-02-11 19:09:22,2019-02-11 19:21:47,2.0,1.91,1.0,N,21,...,10.50,1.0,0.5,0.00,0.0,0.3,12.30,0.0,brooklyn_1,brooklyn_1
19,2782522,2782897,2.0,2019-02-11 18:24:22,2019-02-11 18:30:10,1.0,1.11,1.0,N,22,...,6.50,1.0,0.5,0.00,0.0,0.3,8.30,0.0,brooklyn_1,brooklyn_1
20,1132490,1132811,1.0,2019-02-05 14:36:16,2019-02-05 14:44:06,1.0,1.50,1.0,N,108,...,7.50,0.0,0.5,0.00,0.0,0.3,8.30,0.0,brooklyn_1,brooklyn_1
21,2696484,2696848,1.0,2019-02-11 12:57:06,2019-02-11 13:10:57,1.0,3.60,1.0,N,108,...,13.00,0.0,0.5,0.00,0.0,0.3,13.80,0.0,brooklyn_1,brooklyn_1
22,699633,699947,2.0,2019-02-03 16:32:20,2019-02-03 16:56:27,2.0,7.31,1.0,N,210,...,25.00,0.0,0.5,0.00,0.0,0.3,25.80,0.0,brooklyn_1,brooklyn_1
23,1491884,1492206,1.0,2019-02-06 20:57:16,2019-02-06 21:15:56,2.0,6.20,1.0,N,210,...,21.00,0.5,0.5,0.00,0.0,0.3,22.30,0.0,brooklyn_1,brooklyn_1
24,1662746,1663072,2.0,2019-02-07 13:21:47,2019-02-07 14:02:40,1.0,7.48,1.0,N,210,...,32.50,0.0,0.5,0.00,0.0,0.3,33.30,0.0,brooklyn_1,brooklyn_1
25,2718190,2718554,2.0,2019-02-11 14:40:24,2019-02-11 14:56:41,1.0,5.96,5.0,N,210,...,17.88,0.0,0.5,0.00,0.0,0.3,18.68,0.0,brooklyn_1,brooklyn_1
26,3423276,3423683,1.0,2019-02-14 10:20:50,2019-02-14 10:33:11,1.0,3.80,1.0,N,210,...,14.50,0.0,0.5,0.00,0.0,0.3,15.30,0.0,brooklyn_1,brooklyn_1
27,3464082,3464494,2.0,2019-02-14 13:06:20,2019-02-14 13:35:01,1.0,6.49,1.0,N,210,...,24.00,0.0,0.5,0.00,0.0,0.3,24.80,0.0,brooklyn_1,brooklyn_1
28,1396443,1396764,1.0,2019-02-06 14:04:37,2019-02-06 14:51:52,1.0,8.50,1.0,Y,25,...,37.00,0.0,0.5,0.00,0.0,0.3,37.80,0.0,brooklyn_2,brooklyn_1
29,3569461,3569888,1.0,2019-02-14 20:15:21,2019-02-14 20:45:53,1.0,10.60,1.0,N,33,...,33.00,0.5,0.5,2.00,0.0,0.3,36.30,0.0,brooklyn_2,brooklyn_1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3618775,3046064,3046455,2.0,2019-02-12 21:14:11,2019-02-12 21:14:22,1.0,0.00,1.0,N,1,...,2.50,0.5,0.5,0.00,0.0,0.3,3.80,0.0,unknown,unknown
3618776,3097686,3098077,2.0,2019-02-13 06:36:17,2019-02-13 06:36:18,1.0,0.00,5.0,N,1,...,95.00,0.0,0.0,19.06,0.0,0.3,114.36,0.0,unknown,unknown
3618777,3142220,3142611,1.0,2019-02-13 10:44:45,2019-02-13 10:45:26,1.0,0.00,5.0,N,1,...,85.00,0.0,0.0,17.05,0.0,0.3,102.35,0.0,unknown,unknown
3618778,3144850,3145241,1.0,2019-02-13 10:30:12,2019-02-13 10:30:36,1.0,0.00,5.0,N,1,...,95.00,0.0,0.0,10.00,0.0,0.3,105.30,0.0,unknown,unknown
3618779,3146212,3146603,1.0,2019-02-13 10:30:59,2019-02-13 10:31:36,1.0,1.10,5.0,N,1,...,90.00,0.0,0.0,18.05,0.0,0.3,108.35,0.0,unknown,unknown
3618780,3148873,3149264,2.0,2019-02-13 10:06:46,2019-02-13 10:06:51,1.0,0.00,5.0,N,1,...,95.00,0.0,0.0,0.00,0.0,0.3,95.30,0.0,unknown,unknown
3618781,3194064,3194455,1.0,2019-02-13 14:00:53,2019-02-13 14:01:21,1.0,0.00,5.0,N,1,...,95.00,0.0,0.0,23.80,0.0,0.3,119.10,0.0,unknown,unknown
3618782,3199444,3199835,2.0,2019-02-13 13:03:27,2019-02-13 13:03:41,1.0,0.01,5.0,N,1,...,162.00,0.0,0.0,37.66,26.0,0.3,225.96,0.0,unknown,unknown
3618783,3226817,3227208,1.0,2019-02-13 16:11:27,2019-02-13 16:12:02,1.0,1.70,5.0,N,1,...,75.00,0.0,0.0,27.95,18.0,0.3,121.25,0.0,unknown,unknown
3618784,3229670,3230061,2.0,2019-02-13 16:35:02,2019-02-13 16:36:12,1.0,0.36,5.0,N,1,...,98.00,0.0,0.5,22.26,12.5,0.3,133.56,0.0,unknown,unknown
3618785,3245643,3246034,2.0,2019-02-13 17:08:07,2019-02-13 17:08:32,1.0,0.00,5.0,N,1,...,85.00,0.0,0.5,17.16,0.0,0.3,102.96,0.0,unknown,unknown
3618786,3248539,3248930,2.0,2019-02-13 17:00:04,2019-02-13 17:00:15,1.0,0.33,5.0,N,1,...,116.00,0.0,0.0,23.26,0.0,0.3,139.56,0.0,unknown,unknown
3618787,3251639,3252032,1.0,2019-02-13 17:25:13,2019-02-13 17:25:34,1.0,1.60,5.0,N,1,...,95.00,0.0,0.0,15.00,0.0,0.3,110.30,0.0,unknown,unknown
3618788,3251745,3252138,2.0,2019-02-13 17:04:49,2019-02-13 17:04:56,1.0,0.00,3.0,N,1,...,20.00,1.0,0.0,4.26,0.0,0.3,25.56,0.0,unknown,unknown
3618789,3265223,3265616,2.0,2019-02-13 18:46:03,2019-02-13 18:46:50,1.0,0.00,5.0,N,1,...,120.00,0.0,0.0,10.00,0.0,0.3,130.30,0.0,unknown,unknown
3618790,3284705,3285099,1.0,2019-02-13 19:16:51,2019-02-13 19:18:14,1.0,16.50,5.0,N,1,...,87.00,0.0,0.0,0.00,0.0,0.3,87.30,0.0,unknown,unknown
3618791,3313337,3313731,1.0,2019-02-13 21:10:39,2019-02-13 21:12:46,1.0,4.30,1.0,N,1,...,3.00,0.5,0.5,60.00,10.5,0.3,74.80,0.0,unknown,unknown
3618792,3357196,3357590,2.0,2019-02-14 02:26:21,2019-02-14 02:26:24,1.0,0.00,5.0,N,1,...,25.00,0.0,0.0,3.00,0.0,0.3,28.30,0.0,unknown,unknown
3618793,3361252,3361646,1.0,2019-02-14 04:34:40,2019-02-14 04:34:54,0.0,0.00,5.0,N,1,...,70.00,0.0,0.0,5.00,0.0,0.3,75.30,0.0,unknown,unknown
3618794,3362567,3362961,1.0,2019-02-14 05:59:12,2019-02-14 05:59:59,2.0,0.00,5.0,N,1,...,80.00,0.0,0.0,15.00,20.0,0.3,115.30,0.0,unknown,unknown
3618795,3362759,3363153,1.0,2019-02-14 05:58:14,2019-02-14 05:59:33,1.0,0.20,5.0,N,1,...,90.00,0.0,0.0,15.00,0.0,0.3,105.30,0.0,unknown,unknown
3618796,3363584,3363980,1.0,2019-02-14 05:45:50,2019-02-14 05:46:33,2.0,0.00,5.0,N,1,...,70.00,0.0,0.0,10.00,0.0,0.3,80.30,0.0,unknown,unknown
3618797,3363587,3363983,1.0,2019-02-14 05:42:43,2019-02-14 05:43:25,0.0,0.00,5.0,N,1,...,100.00,0.0,0.0,0.00,0.0,0.3,100.30,0.0,unknown,unknown
3618798,3366877,3367273,1.0,2019-02-14 06:46:25,2019-02-14 06:46:54,1.0,0.00,5.0,N,1,...,83.50,0.0,0.0,16.75,0.0,0.3,100.55,0.0,unknown,unknown
3618799,3443977,3444384,2.0,2019-02-14 12:02:29,2019-02-14 12:02:46,2.0,0.00,5.0,N,1,...,85.00,0.0,0.5,0.00,15.0,0.3,100.80,0.0,unknown,unknown
3618800,3445649,3446056,2.0,2019-02-14 12:26:23,2019-02-14 12:26:25,1.0,0.06,5.0,N,1,...,95.00,0.0,0.0,10.00,0.0,0.3,105.30,0.0,unknown,unknown
3618801,3477148,3477561,1.0,2019-02-14 14:55:13,2019-02-14 14:55:42,2.0,0.00,5.0,N,1,...,110.00,0.0,0.0,0.00,0.0,0.3,110.30,0.0,unknown,unknown
3618802,3503131,3503553,1.0,2019-02-14 16:57:27,2019-02-14 16:57:56,1.0,0.00,5.0,N,1,...,85.00,0.0,0.0,17.05,0.0,0.3,102.35,0.0,unknown,unknown
3618803,3550644,3551071,2.0,2019-02-14 19:56:38,2019-02-14 19:57:38,2.0,0.00,5.0,N,1,...,88.00,0.0,0.5,31.83,17.3,0.3,137.93,0.0,unknown,unknown
3618804,3566106,3566533,1.0,2019-02-14 20:20:59,2019-02-14 20:21:32,1.0,20.60,5.0,N,1,...,120.00,0.0,0.0,15.00,0.0,0.3,135.30,0.0,unknown,unknown

In [3]:
brooklyn_1 = [11,  21,  22,  29,  55,  67, 108, 123, 149, 150, 165, 178, 210]
brooklyn_2 = [25,  33,  40,  52,  54,  65,  66,  97, 106, 181, 195]
brooklyn_3 = [35,  39,  63,  72,  76,  77,  91, 154, 155, 177, 222]
brooklyn_4 = [14,  26,  62,  71,  85,  89, 111, 133, 188, 189, 190, 227, 228, 257]
brooklyn_5 = [17,  34,  36,  37,  49,  61,  80, 112, 217, 225, 255, 256]
queens_1 = [ 9,  15,  16, 171, 252]
queens_2 = [19,  64,  98, 101, 131, 175, 191]
queens_3 = [96, 124, 134, 180, 197, 258]
queens_4 = [7,   8, 145, 146, 179, 193]
queens_5 = [70, 129, 138, 207, 223]
queens_6 = [83, 102, 157, 160, 198, 226, 260]
queens_7 = [2,  27,  30,  86, 117, 132, 201]
queens_8 = [53,  57,  92,  93, 253]
queens_9 = [38, 122, 139, 203, 205, 218, 219]
queens_10 = [56,  82,  95, 173, 196]
queens_11 = [73, 121, 135, 192]
queens_12 = [10,  28, 130, 215, 216]
manhattan_1 = [48,  50, 142, 143, 161, 163, 230]
manhattan_2 = [42,  74, 116, 120, 127, 128, 152, 153, 243, 244]
manhattan_3 = [140, 141, 162, 202, 229, 236, 237, 262, 263]
manhattan_4 = [12,  13,  45,  87,  88, 103, 104, 105, 209, 231, 261]
manhattan_5 = [24,  41,  43,  75, 151, 166, 194, 238, 239]
manhattan_6 = [113, 114, 125, 144, 148, 158, 211, 232, 249]
manhattan_7 = [4,  79, 107, 137, 170, 224, 233]
manhattan_8 = [68,  90, 100, 164, 186, 234, 246]
bronx_1 = [20,  47,  59,  78,  94, 136, 169]
bronx_2 = [182, 185, 212, 213, 248, 250]
bronx_3 = [46,  51,  58, 183, 184, 208, 242]
bronx_4 = [69, 119, 147, 159, 167, 168, 235, 247]
bronx_5 = [18, 174, 200, 220, 240, 241]
bronx_6 = [3,  31,  32,  81, 254, 259]
bronx_7 = [60, 126, 199]
unknown=[264,265,5,6,23,44,84,99,109,110,115,118,156,172,176,187,204,206,214,221,245,251,1]

In [5]:
list_brooklyn_1= [] 

for i in range(0, len(brooklyn_1)):

	 list_brooklyn_1.append(df[(df.PULocationID==brooklyn_1[i])]) 

list_2=[]
for i in range(0, len(list_brooklyn_1)): 

	 list_2.append(list_brooklyn_1[i])
a=pd.concat(list_2) 

a['zone']='brooklyn_1'
list_brooklyn_2= [] 

for i in range(0, len(brooklyn_2)):

	 list_brooklyn_2.append(df[(df.PULocationID==brooklyn_2[i])]) 

list_3=[]
for i in range(0, len(list_brooklyn_2)): 

	 list_3.append(list_brooklyn_2[i])
b=pd.concat(list_3) 

b['zone']='brooklyn_2'
list_brooklyn_3= [] 

for i in range(0, len(brooklyn_3)):

	 list_brooklyn_3.append(df[(df.PULocationID==brooklyn_3[i])]) 

list_4=[]
for i in range(0, len(list_brooklyn_3)): 

	 list_4.append(list_brooklyn_3[i])
c=pd.concat(list_4) 

c['zone']='brooklyn_3'
list_brooklyn_4= [] 

for i in range(0, len(brooklyn_4)):

	 list_brooklyn_4.append(df[(df.PULocationID==brooklyn_4[i])]) 

list_5=[]
for i in range(0, len(list_brooklyn_4)): 

	 list_5.append(list_brooklyn_4[i])
d=pd.concat(list_5) 

d['zone']='brooklyn_4'
list_brooklyn_5= [] 

for i in range(0, len(brooklyn_5)):

	 list_brooklyn_5.append(df[(df.PULocationID==brooklyn_5[i])]) 

list_6=[]
for i in range(0, len(list_brooklyn_5)): 

	 list_6.append(list_brooklyn_5[i])
e=pd.concat(list_6) 

e['zone']='brooklyn_5'
list_queens_1= [] 

for i in range(0, len(queens_1)):

	 list_queens_1.append(df[(df.PULocationID==queens_1[i])]) 

list_7=[]
for i in range(0, len(list_queens_1)): 

	 list_7.append(list_queens_1[i])
f=pd.concat(list_7) 

f['zone']='queens_1'
list_queens_2= [] 

for i in range(0, len(queens_2)):

	 list_queens_2.append(df[(df.PULocationID==queens_2[i])]) 

list_8=[]
for i in range(0, len(list_queens_2)): 

	 list_8.append(list_queens_2[i])
g=pd.concat(list_8) 

g['zone']='queens_2'
list_queens_3= [] 

for i in range(0, len(queens_3)):

	 list_queens_3.append(df[(df.PULocationID==queens_3[i])]) 

list_9=[]
for i in range(0, len(list_queens_3)): 

	 list_9.append(list_queens_3[i])
h=pd.concat(list_9) 

h['zone']='queens_3'
list_queens_4= [] 

for i in range(0, len(queens_4)):

	 list_queens_4.append(df[(df.PULocationID==queens_4[i])]) 

list_10=[]
for i in range(0, len(list_queens_4)): 

	 list_10.append(list_queens_4[i])
i1=pd.concat(list_10) 

i1['zone']='queens_4'
list_queens_5= [] 

for i in range(0, len(queens_5)):

	 list_queens_5.append(df[(df.PULocationID==queens_5[i])]) 

list_11=[]
for i in range(0, len(list_queens_5)): 

	 list_11.append(list_queens_5[i])
j=pd.concat(list_11) 

j['zone']='queens_5'
list_queens_6= [] 

for i in range(0, len(queens_6)):

	 list_queens_6.append(df[(df.PULocationID==queens_6[i])]) 

list_12=[]
for i in range(0, len(list_queens_6)): 

	 list_12.append(list_queens_6[i])
k=pd.concat(list_12) 

k['zone']='queens_6'
list_queens_7= [] 

for i in range(0, len(queens_7)):

	 list_queens_7.append(df[(df.PULocationID==queens_7[i])]) 

list_13=[]
for i in range(0, len(list_queens_7)): 

	 list_13.append(list_queens_7[i])
l=pd.concat(list_13) 

l['zone']='queens_7'
list_queens_8= [] 

for i in range(0, len(queens_8)):

	 list_queens_8.append(df[(df.PULocationID==queens_8[i])]) 

list_14=[]
for i in range(0, len(list_queens_8)): 

	 list_14.append(list_queens_8[i])
m=pd.concat(list_14) 

m['zone']='queens_8'
list_queens_9= [] 

for i in range(0, len(queens_9)):

	 list_queens_9.append(df[(df.PULocationID==queens_9[i])]) 

list_15=[]
for i in range(0, len(list_queens_9)): 

	 list_15.append(list_queens_9[i])
n=pd.concat(list_15) 

n['zone']='queens_9'
list_queens_10= [] 

for i in range(0, len(queens_10)):

	 list_queens_10.append(df[(df.PULocationID==queens_10[i])]) 

list_16=[]
for i in range(0, len(list_queens_10)): 

	 list_16.append(list_queens_10[i])
o=pd.concat(list_16) 

o['zone']='queens_10'
list_queens_11= [] 

for i in range(0, len(queens_11)):

	 list_queens_11.append(df[(df.PULocationID==queens_11[i])]) 

list_17=[]
for i in range(0, len(list_queens_11)): 

	 list_17.append(list_queens_11[i])
p=pd.concat(list_17) 

p['zone']='queens_11'
list_queens_12= [] 

for i in range(0, len(queens_12)):

	 list_queens_12.append(df[(df.PULocationID==queens_12[i])]) 

list_18=[]
for i in range(0, len(list_queens_12)): 

	 list_18.append(list_queens_12[i])
q=pd.concat(list_18) 

q['zone']='queens_12'
list_manhattan_1= [] 

for i in range(0, len(manhattan_1)):

	 list_manhattan_1.append(df[(df.PULocationID==manhattan_1[i])]) 

list_19=[]
for i in range(0, len(list_manhattan_1)): 

	 list_19.append(list_manhattan_1[i])
r=pd.concat(list_19) 

r['zone']='manhattan_1'
list_manhattan_2= [] 

for i in range(0, len(manhattan_2)):

	 list_manhattan_2.append(df[(df.PULocationID==manhattan_2[i])]) 

list_20=[]
for i in range(0, len(list_manhattan_2)): 

	 list_20.append(list_manhattan_2[i])
s=pd.concat(list_20) 

s['zone']='manhattan_2'
list_manhattan_3= [] 

for i in range(0, len(manhattan_3)):

	 list_manhattan_3.append(df[(df.PULocationID==manhattan_3[i])]) 

list_21=[]
for i in range(0, len(list_manhattan_3)): 

	 list_21.append(list_manhattan_3[i])
t=pd.concat(list_21) 

t['zone']='manhattan_3'
list_manhattan_4= [] 

for i in range(0, len(manhattan_4)):

	 list_manhattan_4.append(df[(df.PULocationID==manhattan_4[i])]) 

list_22=[]
for i in range(0, len(list_manhattan_4)): 

	 list_22.append(list_manhattan_4[i])
u=pd.concat(list_22) 

u['zone']='manhattan_4'
list_manhattan_5= [] 

for i in range(0, len(manhattan_5)):

	 list_manhattan_5.append(df[(df.PULocationID==manhattan_5[i])]) 

list_23=[]
for i in range(0, len(list_manhattan_5)): 

	 list_23.append(list_manhattan_5[i])
v=pd.concat(list_23) 

v['zone']='manhattan_5'
list_manhattan_6= [] 

for i in range(0, len(manhattan_6)):

	 list_manhattan_6.append(df[(df.PULocationID==manhattan_6[i])]) 

list_24=[]
for i in range(0, len(list_manhattan_6)): 

	 list_24.append(list_manhattan_6[i])
w=pd.concat(list_24) 

w['zone']='manhattan_6'
list_manhattan_7= [] 

for i in range(0, len(manhattan_7)):

	 list_manhattan_7.append(df[(df.PULocationID==manhattan_7[i])]) 

list_25=[]
for i in range(0, len(list_manhattan_7)): 

	 list_25.append(list_manhattan_7[i])
x=pd.concat(list_25) 

x['zone']='manhattan_7'
list_manhattan_8= [] 

for i in range(0, len(manhattan_8)):

	 list_manhattan_8.append(df[(df.PULocationID==manhattan_8[i])]) 

list_26=[]
for i in range(0, len(list_manhattan_8)): 

	 list_26.append(list_manhattan_8[i])
y=pd.concat(list_26) 

y['zone']='manhattan_8'
list_bronx_1= [] 

for i in range(0, len(bronx_1)):

	 list_bronx_1.append(df[(df.PULocationID==bronx_1[i])]) 

list_27=[]
for i in range(0, len(list_bronx_1)): 

	 list_27.append(list_bronx_1[i])
z=pd.concat(list_27) 

z['zone']='bronx_1'
list_bronx_2= [] 

for i in range(0, len(bronx_2)):

	 list_bronx_2.append(df[(df.PULocationID==bronx_2[i])]) 

list_28=[]
for i in range(0, len(list_bronx_2)): 

	 list_28.append(list_bronx_2[i])
aa=pd.concat(list_28) 

aa['zone']='bronx_2'
list_bronx_3= [] 

for i in range(0, len(bronx_3)):

	 list_bronx_3.append(df[(df.PULocationID==bronx_3[i])]) 

list_29=[]
for i in range(0, len(list_bronx_3)): 

	 list_29.append(list_bronx_3[i])
ab=pd.concat(list_29) 

ab['zone']='bronx_3'
list_bronx_4= [] 

for i in range(0, len(bronx_4)):

	 list_bronx_4.append(df[(df.PULocationID==bronx_4[i])]) 

list_30=[]
for i in range(0, len(list_bronx_4)): 

	 list_30.append(list_bronx_4[i])
ac=pd.concat(list_30) 

ac['zone']='bronx_4'
list_bronx_5= [] 

for i in range(0, len(bronx_5)):

	 list_bronx_5.append(df[(df.PULocationID==bronx_5[i])]) 

list_31=[]
for i in range(0, len(list_bronx_5)): 

	 list_31.append(list_bronx_5[i])
ad=pd.concat(list_31) 

ad['zone']='bronx_5'
list_bronx_6= [] 

for i in range(0, len(bronx_6)):

	 list_bronx_6.append(df[(df.PULocationID==bronx_6[i])]) 

list_32=[]
for i in range(0, len(list_bronx_6)): 

	 list_32.append(list_bronx_6[i])
ae=pd.concat(list_32) 

ae['zone']='bronx_6'
list_bronx_7= [] 

for i in range(0, len(bronx_7)):

	 list_bronx_7.append(df[(df.PULocationID==bronx_7[i])]) 

list_33=[]
for i in range(0, len(list_bronx_7)): 

	 list_33.append(list_bronx_7[i])
af=pd.concat(list_33) 

af['zone']='bronx_7'
list_unknown= [] 

for i in range(0, len(unknown)):

	 list_unknown.append(df[(df.PULocationID==unknown[i])]) 

list_34=[]
for i in range(0, len(list_unknown)): 

	 list_34.append(list_unknown[i])
ag=pd.concat(list_34) 

ag['zone']='unknown'
all_area=pd.concat([a,b,c,d,e,f,g,h,i1,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,aa,ab,ac,ad,ae,af,ag])

In [6]:
all_area

,Unnamed: 0,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,zone
109687,109992,2.0,2019-02-01 12:27:30,2019-02-01 12:42:29,3.0,2.83,1.0,N,11,123,1.0,12.50,0.0,0.5,0.00,0.00,0.3,13.30,0.0,brooklyn_1
381889,382200,2.0,2019-02-02 11:06:00,2019-02-02 11:09:11,3.0,0.00,1.0,N,11,11,2.0,2.50,0.0,0.5,0.00,0.00,0.3,3.30,0.0,brooklyn_1
389779,390090,2.0,2019-02-02 12:46:31,2019-02-02 12:52:13,2.0,0.80,1.0,N,11,22,1.0,6.00,0.0,0.5,0.00,0.00,0.3,6.80,0.0,brooklyn_1
394676,394987,2.0,2019-02-02 12:46:29,2019-02-02 13:17:20,1.0,12.93,1.0,N,11,222,1.0,39.00,0.0,0.5,0.00,0.00,0.3,39.80,0.0,brooklyn_1
415823,416134,2.0,2019-02-02 13:28:19,2019-02-02 13:37:48,1.0,1.76,1.0,N,11,21,2.0,8.50,0.0,0.5,0.00,0.00,0.3,9.30,0.0,brooklyn_1
471552,471863,1.0,2019-02-02 17:19:00,2019-02-02 17:19:09,1.0,0.00,1.0,N,11,11,2.0,2.50,0.0,0.5,0.00,0.00,0.3,3.30,0.0,brooklyn_1
531477,531788,1.0,2019-02-02 21:42:33,2019-02-02 22:18:23,1.0,12.80,1.0,N,11,256,1.0,40.00,3.0,0.5,2.19,0.00,0.3,45.99,2.5,brooklyn_1
559702,560016,2.0,2019-02-02 23:53:49,2019-02-03 00:15:50,2.0,4.21,1.0,N,11,155,1.0,16.50,0.5,0.5,0.00,0.00,0.3,17.80,0.0,brooklyn_1
606107,606421,1.0,2019-02-03 05:12:47,2019-02-03 05:13:09,1.0,0.00,5.0,N,11,11,1.0,55.00,0.0,0.0,0.00,0.00,0.3,55.30,0.0,brooklyn_1
619405,619719,2.0,2019-02-03 09:45:23,2019-02-03 10:26:15,1.0,24.06,5.0,N,11,95,1.0,58.87,0.0,0.5,0.00,0.00,0.3,59.67,0.0,brooklyn_1
671191,671505,2.0,2019-02-03 13:12:25,2019-02-03 13:19:07,1.0,1.33,1.0,N,11,14,1.0,7.00,0.0,0.5,1.56,0.00,0.3,9.36,0.0,brooklyn_1
684292,684606,1.0,2019-02-03 15:46:49,2019-02-03 15:48:03,1.0,0.00,5.0,N,11,11,1.0,47.00,0.0,0.0,9.45,0.00,0.3,56.75,0.0,brooklyn_1
706153,706467,2.0,2019-02-03 16:42:40,2019-02-03 16:56:10,1.0,1.89,1.0,N,11,11,1.0,10.50,0.0,0.5,0.00,0.00,0.3,11.30,0.0,brooklyn_1
716856,717170,2.0,2019-02-03 17:45:34,2019-02-03 18:22:24,1.0,17.44,5.0,N,11,229,1.0,51.25,0.0,0.5,0.00,5.76,0.3,57.81,0.0,brooklyn_1
746171,746486,2.0,2019-02-03 19:00:20,2019-02-03 19:10:59,1.0,1.35,1.0,N,11,11,1.0,8.50,0.0,0.5,0.00,0.00,0.3,9.30,0.0,brooklyn_1
783714,784029,2.0,2019-02-03 23:03:04,2019-02-03 23:28:43,5.0,7.40,1.0,N,11,210,1.0,26.50,0.5,0.5,0.00,0.00,0.3,27.80,0.0,brooklyn_1
808931,809246,1.0,2019-02-04 07:16:15,2019-02-04 07:57:19,1.0,16.70,1.0,N,11,95,1.0,50.00,0.0,0.5,0.00,0.00,0.3,50.80,0.0,brooklyn_1
813846,814161,2.0,2019-02-04 07:09:44,2019-02-04 07:35:58,1.0,10.07,5.0,N,11,261,1.0,30.98,0.0,0.5,0.00,5.76,0.3,37.54,0.0,brooklyn_1
881996,882315,1.0,2019-02-04 13:38:40,2019-02-04 14:28:07,1.0,16.00,1.0,N,11,166,1.0,50.00,2.5,0.5,17.70,5.76,0.3,76.76,2.5,brooklyn_1
884392,884711,2.0,2019-02-04 12:57:49,2019-02-04 13:06:47,1.0,1.37,1.0,N,11,11,1.0,7.50,0.0,0.5,0.00,0.00,0.3,8.30,0.0,brooklyn_1
888648,888967,2.0,2019-02-04 14:14:48,2019-02-04 14:15:01,6.0,0.07,1.0,N,11,11,2.0,2.50,0.0,0.5,0.00,0.00,0.3,3.30,0.0,brooklyn_1
906829,907148,1.0,2019-02-04 15:56:17,2019-02-04 16:06:13,1.0,2.00,1.0,N,11,108,1.0,9.00,0.0,0.5,0.00,0.00,0.3,9.80,0.0,brooklyn_1
920115,920434,2.0,2019-02-04 16:47:28,2019-02-04 17:40:07,1.0,21.53,1.0,N,11,74,1.0,60.00,1.0,0.5,0.00,5.76,0.3,70.06,2.5,brooklyn_1
929129,929448,1.0,2019-02-04 17:36:35,2019-02-04 17:50:44,1.0,2.40,1.0,N,11,108,1.0,11.50,1.0,0.5,0.00,0.00,0.3,13.30,0.0,brooklyn_1
1038263,1038582,2.0,2019-02-05 07:25:26,2019-02-05 07:25:58,1.0,0.42,1.0,N,11,14,2.0,3.50,0.0,0.5,0.00,0.00,0.3,4.30,0.0,brooklyn_1
1039499,1039818,2.0,2019-02-05 07:51:10,2019-02-05 08:32:02,1.0,15.82,5.0,N,11,233,1.0,44.20,0.0,0.5,0.00,5.76,0.3,50.76,0.0,brooklyn_1
1058737,1059056,2.0,2019-02-05 08:31:14,2019-02-05 08:46:05,1.0,6.24,1.0,N,11,14,1.0,20.00,0.0,0.5,0.00,0.00,0.3,20.80,0.0,brooklyn_1
1119645,1119966,2.0,2019-02-05 13:11:18,2019-02-05 13:22:58,1.0,1.59,1.0,N,11,22,1.0,9.50,0.0,0.5,0.00,0.00,0.3,10.30,0.0,brooklyn_1
1134265,1134586,1.0,2019-02-05 14:59:35,2019-02-05 15:12:17,1.0,2.60,1.0,N,11,67,2.0,11.50,0.0,0.5,0.00,0.00,0.3,12.30,0.0,brooklyn_1
1151446,1151767,2.0,2019-02-05 15:48:00,2019-02-05 16:12:16,3.0,3.31,1.0,N,11,141,2.0,16.50,0.0,0.5,0.00,0.00,0.3,17.30,0.0,brooklyn_1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3137371,3137762,2.0,2019-02-13 09:41:15,2019-02-13 10:08:07,1.0,1.64,1.0,N,1,142,1.0,16.50,0.0,0.5,2.97,0.00,0.3,22.77,2.5,unknown
3142220,3142611,1.0,2019-02-13 10:44:45,2019-02-13 10:45:26,1.0,0.00,5.0,N,1,1,1.0,85.00,0.0,0.0,17.05,0.00,0.3,102.35,0.0,unknown
3144850,3145241,1.0,2019-02-13 10:30:12,2019-02-13 10:30:36,1.0,0.00,5.0,N,1,1,1.0,95.00,0.0,0.0,10.00,0.00,0.3,105.30,0.0,unknown
3146212,3146603,1.0,2019-02-13 10:30:59,2019-02-13 10:31:36,1.0,1.10,5.0,N,1,1,1.0,90.00,0.0,0.0,18.05,0.00,0.3,108.35,0.0,unknown
3148873,3149264,2.0,2019-02-13 10:06:46,2019-02-13 10:06:51,1.0,0.00,5.0,N,1,1,1.0,95.00,0.0,0.0,0.00,0.00,0.3,95.30,0.0,unknown
3194064,3194455,1.0,2019-02-13 14:00:53,2019-02-13 14:01:21,1.0,0.00,5.0,N,1,1,1.0,95.00,0.0,0.0,23.80,0.00,0.3,119.10,0.0,unknown
3199444,3199835,2.0,2019-02-13 13:03:27,2019-02-13 13:03:41,1.0,0.01,5.0,N,1,1,1.0,162.00,0.0,0.0,37.66,26.00,0.3,225.96,0.0,unknown
3226817,3227208,1.0,2019-02-13 16:11:27,2019-02-13 16:12:02,1.0,1.70,5.0,N,1,1,1.0,75.00,0.0,0.0,27.95,18.00,0.3,121.25,0.0,unknown
3229670,3230061,2.0,2019-02-13 16:35:02,2019-02-13 16:36:12,1.0,0.36,5.0,N,1,1,1.0,98.00,0.0,0.5,22.26,12.50,0.3,133.56,0.0,unknown
3245643,3246034,2.0,2019-02-13 17:08:07,2019-02-13 17:08:32,1.0,0.00,5.0,N,1,1,1.0,85.00,0.0,0.5,17.16,0.00,0.3,102.96,0.0,unknown
3248539,3248930,2.0,2019-02-13 17:00:04,2019-02-13 17:00:15,1.0,0.33,5.0,N,1,1,1.0,116.00,0.0,0.0,23.26,0.00,0.3,139.56,0.0,unknown
3251639,3252032,1.0,2019-02-13 17:25:13,2019-02-13 17:25:34,1.0,1.60,5.0,N,1,1,1.0,95.00,0.0,0.0,15.00,0.00,0.3,110.30,0.0,unknown
3251745,3252138,2.0,2019-02-13 17:04:49,2019-02-13 17:04:56,1.0,0.00,3.0,N,1,1,1.0,20.00,1.0,0.0,4.26,0.00,0.3,25.56,0.0,unknown
3265223,3265616,2.0,2019-02-13 18:46:03,2019-02-13 18:46:50,1.0,0.00,5.0,N,1,1,1.0,120.00,0.0,0.0,10.00,0.00,0.3,130.30,0.0,unknown
3276186,3276580,2.0,2019-02-13 19:22:56,2019-02-13 19:57:48,1.0,27.88,3.0,N,1,151,1.0,90.50,1.0,0.0,18.36,0.00,0.3,110.16,0.0,unknown
3284705,3285099,1.0,2019-02-13 19:16:51,2019-02-13 19:18:14,1.0,16.50,5.0,N,1,1,1.0,87.00,0.0,0.0,0.00,0.00,0.3,87.30,0.0,unknown
3313337,3313731,1.0,2019-02-13 21:10:39,2019-02-13 21:12:46,1.0,4.30,1.0,N,1,1,1.0,3.00,0.5,0.5,60.00,10.50,0.3,74.80,0.0,unknown
3357196,3357590,2.0,2019-02-14 02:26:21,2019-02-14 02:26:24,1.0,0.00,5.0,N,1,1,1.0,25.00,0.0,0.0,3.00,0.00,0.3,28.30,0.0,unknown
3361252,3361646,1.0,2019-02-14 04:34:40,2019-02-14 04:34:54,0.0,0.00,5.0,N,1,1,1.0,70.00,0.0,0.0,5.00,0.00,0.3,75.30,0.0,unknown
3362567,3362961,1.0,2019-02-14 05:59:12,2019-02-14 05:59:59,2.0,0.00,5.0,N,1,1,1.0,80.00,0.0,0.0,15.00,20.00,0.3,115.30,0.0,unknown
3362759,3363153,1.0,2019-02-14 05:58:14,2019-02-14 05:59:33,1.0,0.20,5.0,N,1,1,1.0,90.00,0.0,0.0,15.00,0.00,0.3,105.30,0.0,unknown
3363584,3363980,1.0,2019-02-14 05:45:50,2019-02-14 05:46:33,2.0,0.00,5.0,N,1,1,1.0,70.00,0.0,0.0,10.00,0.00,0.3,80.30,0.0,unknown
3363587,3363983,1.0,2019-02-14 05:42:43,2019-02-14 05:43:25,0.0,0.00,5.0,N,1,1,1.0,100.00,0.0,0.0,0.00,0.00,0.3,100.30,0.0,unknown
3366877,3367273,1.0,2019-02-14 06:46:25,2019-02-14 06:46:54,1.0,0.00,5.0,N,1,1,1.0,83.50,0.0,0.0,16.75,0.00,0.3,100.55,0.0,unknown
3443977,3444384,2.0,2019-02-14 12:02:29,2019-02-14 12:02:46,2.0,0.00,5.0,N,1,1,1.0,85.00,0.0,0.5,0.00,15.00,0.3,100.80,0.0,unknown
3445649,3446056,2.0,2019-02-14 12:26:23,2019-02-14 12:26:25,1.0,0.06,5.0,N,1,1,1.0,95.00,0.0,0.0,10.00,0.00,0.3,105.30,0.0,unknown
3477148,3477561,1.0,2019-02-14 14:55:13,2019-02-14 14:55:42,2.0,0.00,5.0,N,1,1,1.0,110.00,0.0,0.0,0.00,0.00,0.3,110.30,0.0,unknown
3503131,3503553,1.0,2019-02-14 16:57:27,2019-02-14 16:57:56,1.0,0.00,5.0,N,1,1,1.0,85.00,0.0,0.0,17.05,0.00,0.3,102.35,0.0,unknown
3550644,3551071,2.0,2019-02-14 19:56:38,2019-02-14 19:57:38,2.0,0.00,5.0,N,1,1,1.0,88.00,0.0,0.5,31.83,17.30,0.3,137.93,0.0,unknown
3566106,3566533,1.0,2019-02-14 20:20:59,2019-02-14 20:21:32,1.0,20.60,5.0,N,1,1,1.0,120.00,0.0,0.0,15.00,0.00,0.3,135.30,0.0,unknown

In [7]:
dropbrooklyn_1=[]
for i in range(0, len(brooklyn_1)):
	dropbrooklyn_1.append(all_area[(all_area.DOLocationID==brooklyn_1[i])])
list_2=[]
for i in range(0, len(dropbrooklyn_1)):
	list_2.append(dropbrooklyn_1[i])
aa=pd.concat(list_2)
aa['zone_drop']='brooklyn_1'
dropbrooklyn_2=[]
for i in range(0, len(brooklyn_2)):
	dropbrooklyn_2.append(all_area[(all_area.DOLocationID==brooklyn_2[i])])
list_3=[]
for i in range(0, len(dropbrooklyn_2)):
	list_3.append(dropbrooklyn_2[i])
bb=pd.concat(list_3)
bb['zone_drop']='brooklyn_2'
dropbrooklyn_3=[]
for i in range(0, len(brooklyn_3)):
	dropbrooklyn_3.append(all_area[(all_area.DOLocationID==brooklyn_3[i])])
list_4=[]
for i in range(0, len(dropbrooklyn_3)):
	list_4.append(dropbrooklyn_3[i])
cc=pd.concat(list_4)
cc['zone_drop']='brooklyn_3'
dropbrooklyn_4=[]
for i in range(0, len(brooklyn_4)):
	dropbrooklyn_4.append(all_area[(all_area.DOLocationID==brooklyn_4[i])])
list_5=[]
for i in range(0, len(dropbrooklyn_4)):
	list_5.append(dropbrooklyn_4[i])
dd=pd.concat(list_5)
dd['zone_drop']='brooklyn_4'
dropbrooklyn_5=[]
for i in range(0, len(brooklyn_5)):
	dropbrooklyn_5.append(all_area[(all_area.DOLocationID==brooklyn_5[i])])
list_6=[]
for i in range(0, len(dropbrooklyn_5)):
	list_6.append(dropbrooklyn_5[i])
ee=pd.concat(list_6)
ee['zone_drop']='brooklyn_5'
dropqueens_1=[]
for i in range(0, len(queens_1)):
	dropqueens_1.append(all_area[(all_area.DOLocationID==queens_1[i])])
list_7=[]
for i in range(0, len(dropqueens_1)):
	list_7.append(dropqueens_1[i])
ff=pd.concat(list_7)
ff['zone_drop']='queens_1'
dropqueens_2=[]
for i in range(0, len(queens_2)):
	dropqueens_2.append(all_area[(all_area.DOLocationID==queens_2[i])])
list_8=[]
for i in range(0, len(dropqueens_2)):
	list_8.append(dropqueens_2[i])
gg=pd.concat(list_8)
gg['zone_drop']='queens_2'
dropqueens_3=[]
for i in range(0, len(queens_3)):
	dropqueens_3.append(all_area[(all_area.DOLocationID==queens_3[i])])
list_9=[]
for i in range(0, len(dropqueens_3)):
	list_9.append(dropqueens_3[i])
hh=pd.concat(list_9)
hh['zone_drop']='queens_3'
dropqueens_4=[]
for i in range(0, len(queens_4)):
	dropqueens_4.append(all_area[(all_area.DOLocationID==queens_4[i])])
list_10=[]
for i in range(0, len(dropqueens_4)):
	list_10.append(dropqueens_4[i])
i1i1=pd.concat(list_10)
i1i1['zone_drop']='queens_4'
dropqueens_5=[]
for i in range(0, len(queens_5)):
	dropqueens_5.append(all_area[(all_area.DOLocationID==queens_5[i])])
list_11=[]
for i in range(0, len(dropqueens_5)):
	list_11.append(dropqueens_5[i])
jj=pd.concat(list_11)
jj['zone_drop']='queens_5'
dropqueens_6=[]
for i in range(0, len(queens_6)):
	dropqueens_6.append(all_area[(all_area.DOLocationID==queens_6[i])])
list_12=[]
for i in range(0, len(dropqueens_6)):
	list_12.append(dropqueens_6[i])
kk=pd.concat(list_12)
kk['zone_drop']='queens_6'
dropqueens_7=[]
for i in range(0, len(queens_7)):
	dropqueens_7.append(all_area[(all_area.DOLocationID==queens_7[i])])
list_13=[]
for i in range(0, len(dropqueens_7)):
	list_13.append(dropqueens_7[i])
ll=pd.concat(list_13)
ll['zone_drop']='queens_7'
dropqueens_8=[]
for i in range(0, len(queens_8)):
	dropqueens_8.append(all_area[(all_area.DOLocationID==queens_8[i])])
list_14=[]
for i in range(0, len(dropqueens_8)):
	list_14.append(dropqueens_8[i])
mm=pd.concat(list_14)
mm['zone_drop']='queens_8'
dropqueens_9=[]
for i in range(0, len(queens_9)):
	dropqueens_9.append(all_area[(all_area.DOLocationID==queens_9[i])])
list_15=[]
for i in range(0, len(dropqueens_9)):
	list_15.append(dropqueens_9[i])
nn=pd.concat(list_15)
nn['zone_drop']='queens_9'
dropqueens_10=[]
for i in range(0, len(queens_10)):
	dropqueens_10.append(all_area[(all_area.DOLocationID==queens_10[i])])
list_16=[]
for i in range(0, len(dropqueens_10)):
	list_16.append(dropqueens_10[i])
oo=pd.concat(list_16)
oo['zone_drop']='queens_10'
dropqueens_11=[]
for i in range(0, len(queens_11)):
	dropqueens_11.append(all_area[(all_area.DOLocationID==queens_11[i])])
list_17=[]
for i in range(0, len(dropqueens_11)):
	list_17.append(dropqueens_11[i])
pp=pd.concat(list_17)
pp['zone_drop']='queens_11'
dropqueens_12=[]
for i in range(0, len(queens_12)):
	dropqueens_12.append(all_area[(all_area.DOLocationID==queens_12[i])])
list_18=[]
for i in range(0, len(dropqueens_12)):
	list_18.append(dropqueens_12[i])
qq=pd.concat(list_18)
qq['zone_drop']='queens_12'
dropmanhattan_1=[]
for i in range(0, len(manhattan_1)):
	dropmanhattan_1.append(all_area[(all_area.DOLocationID==manhattan_1[i])])
list_19=[]
for i in range(0, len(dropmanhattan_1)):
	list_19.append(dropmanhattan_1[i])
rr=pd.concat(list_19)
rr['zone_drop']='manhattan_1'
dropmanhattan_2=[]
for i in range(0, len(manhattan_2)):
	dropmanhattan_2.append(all_area[(all_area.DOLocationID==manhattan_2[i])])
list_20=[]
for i in range(0, len(dropmanhattan_2)):
	list_20.append(dropmanhattan_2[i])
ss=pd.concat(list_20)
ss['zone_drop']='manhattan_2'
dropmanhattan_3=[]
for i in range(0, len(manhattan_3)):
	dropmanhattan_3.append(all_area[(all_area.DOLocationID==manhattan_3[i])])
list_21=[]
for i in range(0, len(dropmanhattan_3)):
	list_21.append(dropmanhattan_3[i])
tt=pd.concat(list_21)
tt['zone_drop']='manhattan_3'
dropmanhattan_4=[]
for i in range(0, len(manhattan_4)):
	dropmanhattan_4.append(all_area[(all_area.DOLocationID==manhattan_4[i])])
list_22=[]
for i in range(0, len(dropmanhattan_4)):
	list_22.append(dropmanhattan_4[i])
uu=pd.concat(list_22)
uu['zone_drop']='manhattan_4'
dropmanhattan_5=[]
for i in range(0, len(manhattan_5)):
	dropmanhattan_5.append(all_area[(all_area.DOLocationID==manhattan_5[i])])
list_23=[]
for i in range(0, len(dropmanhattan_5)):
	list_23.append(dropmanhattan_5[i])
vv=pd.concat(list_23)
vv['zone_drop']='manhattan_5'
dropmanhattan_6=[]
for i in range(0, len(manhattan_6)):
	dropmanhattan_6.append(all_area[(all_area.DOLocationID==manhattan_6[i])])
list_24=[]
for i in range(0, len(dropmanhattan_6)):
	list_24.append(dropmanhattan_6[i])
ww=pd.concat(list_24)
ww['zone_drop']='manhattan_6'
dropmanhattan_7=[]
for i in range(0, len(manhattan_7)):
	dropmanhattan_7.append(all_area[(all_area.DOLocationID==manhattan_7[i])])
list_25=[]
for i in range(0, len(dropmanhattan_7)):
	list_25.append(dropmanhattan_7[i])
xx=pd.concat(list_25)
xx['zone_drop']='manhattan_7'
dropmanhattan_8=[]
for i in range(0, len(manhattan_8)):
	dropmanhattan_8.append(all_area[(all_area.DOLocationID==manhattan_8[i])])
list_26=[]
for i in range(0, len(dropmanhattan_8)):
	list_26.append(dropmanhattan_8[i])
yy=pd.concat(list_26)
yy['zone_drop']='manhattan_8'
dropbronx_1=[]
for i in range(0, len(bronx_1)):
	dropbronx_1.append(all_area[(all_area.DOLocationID==bronx_1[i])])
list_27=[]
for i in range(0, len(dropbronx_1)):
	list_27.append(dropbronx_1[i])
zz=pd.concat(list_27)
zz['zone_drop']='bronx_1'
dropbronx_2=[]
for i in range(0, len(bronx_2)):
	dropbronx_2.append(all_area[(all_area.DOLocationID==bronx_2[i])])
list_28=[]
for i in range(0, len(dropbronx_2)):
	list_28.append(dropbronx_2[i])
aaaa=pd.concat(list_28)
aaaa['zone_drop']='bronx_2'
dropbronx_3=[]
for i in range(0, len(bronx_3)):
	dropbronx_3.append(all_area[(all_area.DOLocationID==bronx_3[i])])
list_29=[]
for i in range(0, len(dropbronx_3)):
	list_29.append(dropbronx_3[i])
abab=pd.concat(list_29)
abab['zone_drop']='bronx_3'
dropbronx_4=[]
for i in range(0, len(bronx_4)):
	dropbronx_4.append(all_area[(all_area.DOLocationID==bronx_4[i])])
list_30=[]
for i in range(0, len(dropbronx_4)):
	list_30.append(dropbronx_4[i])
acac=pd.concat(list_30)
acac['zone_drop']='bronx_4'
dropbronx_5=[]
for i in range(0, len(bronx_5)):
	dropbronx_5.append(all_area[(all_area.DOLocationID==bronx_5[i])])
list_31=[]
for i in range(0, len(dropbronx_5)):
	list_31.append(dropbronx_5[i])
adad=pd.concat(list_31)
adad['zone_drop']='bronx_5'
dropbronx_6=[]
for i in range(0, len(bronx_6)):
	dropbronx_6.append(all_area[(all_area.DOLocationID==bronx_6[i])])
list_32=[]
for i in range(0, len(dropbronx_6)):
	list_32.append(dropbronx_6[i])
aeae=pd.concat(list_32)
aeae['zone_drop']='bronx_6'
dropbronx_7=[]
for i in range(0, len(bronx_7)):
	dropbronx_7.append(all_area[(all_area.DOLocationID==bronx_7[i])])
list_33=[]
for i in range(0, len(dropbronx_7)):
	list_33.append(dropbronx_7[i])
afaf=pd.concat(list_33)
afaf['zone_drop']='bronx_7'

dropunknown=[]
for i in range(0, len(unknown)):
	dropunknown.append(all_area[(all_area.DOLocationID==unknown[i])])
list_34=[]
for i in range(0, len(dropunknown)):
	list_34.append(dropunknown[i])
agag=pd.concat(list_34)
agag['zone_drop']='unknown'
all_1=pd.concat([aa,bb,cc,dd,ee,ff,gg,hh,i1i1,jj,kk,ll,mm,nn,oo,pp,qq,rr,ss,tt,uu,vv,ww,xx,yy,zz,aaaa,abab,acac,adad,aeae,afaf,agag])

In [8]:
all_1

,Unnamed: 0,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,...,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,zone,zone_drop
381889,382200,2.0,2019-02-02 11:06:00,2019-02-02 11:09:11,3.0,0.00,1.0,N,11,11,...,2.50,0.0,0.5,0.00,0.0,0.3,3.30,0.0,brooklyn_1,brooklyn_1
471552,471863,1.0,2019-02-02 17:19:00,2019-02-02 17:19:09,1.0,0.00,1.0,N,11,11,...,2.50,0.0,0.5,0.00,0.0,0.3,3.30,0.0,brooklyn_1,brooklyn_1
606107,606421,1.0,2019-02-03 05:12:47,2019-02-03 05:13:09,1.0,0.00,5.0,N,11,11,...,55.00,0.0,0.0,0.00,0.0,0.3,55.30,0.0,brooklyn_1,brooklyn_1
684292,684606,1.0,2019-02-03 15:46:49,2019-02-03 15:48:03,1.0,0.00,5.0,N,11,11,...,47.00,0.0,0.0,9.45,0.0,0.3,56.75,0.0,brooklyn_1,brooklyn_1
706153,706467,2.0,2019-02-03 16:42:40,2019-02-03 16:56:10,1.0,1.89,1.0,N,11,11,...,10.50,0.0,0.5,0.00,0.0,0.3,11.30,0.0,brooklyn_1,brooklyn_1
746171,746486,2.0,2019-02-03 19:00:20,2019-02-03 19:10:59,1.0,1.35,1.0,N,11,11,...,8.50,0.0,0.5,0.00,0.0,0.3,9.30,0.0,brooklyn_1,brooklyn_1
884392,884711,2.0,2019-02-04 12:57:49,2019-02-04 13:06:47,1.0,1.37,1.0,N,11,11,...,7.50,0.0,0.5,0.00,0.0,0.3,8.30,0.0,brooklyn_1,brooklyn_1
888648,888967,2.0,2019-02-04 14:14:48,2019-02-04 14:15:01,6.0,0.07,1.0,N,11,11,...,2.50,0.0,0.5,0.00,0.0,0.3,3.30,0.0,brooklyn_1,brooklyn_1
2010441,2010778,2.0,2019-02-08 18:24:33,2019-02-08 18:24:53,1.0,0.00,1.0,N,11,11,...,2.50,1.0,0.5,0.00,0.0,0.3,4.30,0.0,brooklyn_1,brooklyn_1
2662020,2662384,2.0,2019-02-11 09:17:31,2019-02-11 09:24:20,1.0,1.30,1.0,N,11,11,...,7.00,0.0,0.5,0.00,0.0,0.3,7.80,0.0,brooklyn_1,brooklyn_1
2665624,2665988,1.0,2019-02-11 10:16:24,2019-02-11 10:19:05,1.0,19.40,1.0,N,11,11,...,3.50,0.0,0.5,0.00,0.0,0.3,4.30,0.0,brooklyn_1,brooklyn_1
2718189,2718553,2.0,2019-02-11 14:01:34,2019-02-11 14:11:42,2.0,1.72,1.0,N,11,11,...,9.00,0.0,0.5,0.00,0.0,0.3,9.80,0.0,brooklyn_1,brooklyn_1
2849879,2850257,1.0,2019-02-12 02:11:59,2019-02-12 02:14:18,1.0,0.50,1.0,N,11,11,...,4.00,3.0,0.5,0.00,0.0,0.3,7.80,2.5,brooklyn_1,brooklyn_1
3088803,3089194,2.0,2019-02-13 02:42:36,2019-02-13 02:42:40,2.0,0.00,1.0,N,11,11,...,2.50,0.5,0.5,0.00,0.0,0.3,3.80,0.0,brooklyn_1,brooklyn_1
3436910,3437317,2.0,2019-02-14 12:00:08,2019-02-14 12:06:17,1.0,1.02,1.0,N,11,11,...,6.00,0.0,0.5,0.00,0.0,0.3,6.80,0.0,brooklyn_1,brooklyn_1
122335,122641,2.0,2019-02-01 13:44:28,2019-02-01 13:59:03,1.0,1.69,1.0,N,21,11,...,11.00,0.0,0.5,0.00,0.0,0.3,11.80,0.0,brooklyn_1,brooklyn_1
2534118,2534476,2.0,2019-02-10 16:52:05,2019-02-10 16:58:23,3.0,1.44,1.0,N,21,11,...,7.00,0.0,0.5,1.95,0.0,0.3,9.75,0.0,brooklyn_1,brooklyn_1
2705444,2705808,2.0,2019-02-11 13:33:22,2019-02-11 13:43:43,2.0,1.23,1.0,N,21,11,...,8.50,0.0,0.5,0.00,0.0,0.3,9.30,0.0,brooklyn_1,brooklyn_1
2791152,2791528,2.0,2019-02-11 19:09:22,2019-02-11 19:21:47,2.0,1.91,1.0,N,21,11,...,10.50,1.0,0.5,0.00,0.0,0.3,12.30,0.0,brooklyn_1,brooklyn_1
2782522,2782897,2.0,2019-02-11 18:24:22,2019-02-11 18:30:10,1.0,1.11,1.0,N,22,11,...,6.50,1.0,0.5,0.00,0.0,0.3,8.30,0.0,brooklyn_1,brooklyn_1
1132490,1132811,1.0,2019-02-05 14:36:16,2019-02-05 14:44:06,1.0,1.50,1.0,N,108,11,...,7.50,0.0,0.5,0.00,0.0,0.3,8.30,0.0,brooklyn_1,brooklyn_1
2696484,2696848,1.0,2019-02-11 12:57:06,2019-02-11 13:10:57,1.0,3.60,1.0,N,108,11,...,13.00,0.0,0.5,0.00,0.0,0.3,13.80,0.0,brooklyn_1,brooklyn_1
699633,699947,2.0,2019-02-03 16:32:20,2019-02-03 16:56:27,2.0,7.31,1.0,N,210,11,...,25.00,0.0,0.5,0.00,0.0,0.3,25.80,0.0,brooklyn_1,brooklyn_1
1491884,1492206,1.0,2019-02-06 20:57:16,2019-02-06 21:15:56,2.0,6.20,1.0,N,210,11,...,21.00,0.5,0.5,0.00,0.0,0.3,22.30,0.0,brooklyn_1,brooklyn_1
1662746,1663072,2.0,2019-02-07 13:21:47,2019-02-07 14:02:40,1.0,7.48,1.0,N,210,11,...,32.50,0.0,0.5,0.00,0.0,0.3,33.30,0.0,brooklyn_1,brooklyn_1
2718190,2718554,2.0,2019-02-11 14:40:24,2019-02-11 14:56:41,1.0,5.96,5.0,N,210,11,...,17.88,0.0,0.5,0.00,0.0,0.3,18.68,0.0,brooklyn_1,brooklyn_1
3423276,3423683,1.0,2019-02-14 10:20:50,2019-02-14 10:33:11,1.0,3.80,1.0,N,210,11,...,14.50,0.0,0.5,0.00,0.0,0.3,15.30,0.0,brooklyn_1,brooklyn_1
3464082,3464494,2.0,2019-02-14 13:06:20,2019-02-14 13:35:01,1.0,6.49,1.0,N,210,11,...,24.00,0.0,0.5,0.00,0.0,0.3,24.80,0.0,brooklyn_1,brooklyn_1
1396443,1396764,1.0,2019-02-06 14:04:37,2019-02-06 14:51:52,1.0,8.50,1.0,Y,25,11,...,37.00,0.0,0.5,0.00,0.0,0.3,37.80,0.0,brooklyn_2,brooklyn_1
3569461,3569888,1.0,2019-02-14 20:15:21,2019-02-14 20:45:53,1.0,10.60,1.0,N,33,11,...,33.00,0.5,0.5,2.00,0.0,0.3,36.30,0.0,brooklyn_2,brooklyn_1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3046064,3046455,2.0,2019-02-12 21:14:11,2019-02-12 21:14:22,1.0,0.00,1.0,N,1,1,...,2.50,0.5,0.5,0.00,0.0,0.3,3.80,0.0,unknown,unknown
3097686,3098077,2.0,2019-02-13 06:36:17,2019-02-13 06:36:18,1.0,0.00,5.0,N,1,1,...,95.00,0.0,0.0,19.06,0.0,0.3,114.36,0.0,unknown,unknown
3142220,3142611,1.0,2019-02-13 10:44:45,2019-02-13 10:45:26,1.0,0.00,5.0,N,1,1,...,85.00,0.0,0.0,17.05,0.0,0.3,102.35,0.0,unknown,unknown
3144850,3145241,1.0,2019-02-13 10:30:12,2019-02-13 10:30:36,1.0,0.00,5.0,N,1,1,...,95.00,0.0,0.0,10.00,0.0,0.3,105.30,0.0,unknown,unknown
3146212,3146603,1.0,2019-02-13 10:30:59,2019-02-13 10:31:36,1.0,1.10,5.0,N,1,1,...,90.00,0.0,0.0,18.05,0.0,0.3,108.35,0.0,unknown,unknown
3148873,3149264,2.0,2019-02-13 10:06:46,2019-02-13 10:06:51,1.0,0.00,5.0,N,1,1,...,95.00,0.0,0.0,0.00,0.0,0.3,95.30,0.0,unknown,unknown
3194064,3194455,1.0,2019-02-13 14:00:53,2019-02-13 14:01:21,1.0,0.00,5.0,N,1,1,...,95.00,0.0,0.0,23.80,0.0,0.3,119.10,0.0,unknown,unknown
3199444,3199835,2.0,2019-02-13 13:03:27,2019-02-13 13:03:41,1.0,0.01,5.0,N,1,1,...,162.00,0.0,0.0,37.66,26.0,0.3,225.96,0.0,unknown,unknown
3226817,3227208,1.0,2019-02-13 16:11:27,2019-02-13 16:12:02,1.0,1.70,5.0,N,1,1,...,75.00,0.0,0.0,27.95,18.0,0.3,121.25,0.0,unknown,unknown
3229670,3230061,2.0,2019-02-13 16:35:02,2019-02-13 16:36:12,1.0,0.36,5.0,N,1,1,...,98.00,0.0,0.5,22.26,12.5,0.3,133.56,0.0,unknown,unknown
3245643,3246034,2.0,2019-02-13 17:08:07,2019-02-13 17:08:32,1.0,0.00,5.0,N,1,1,...,85.00,0.0,0.5,17.16,0.0,0.3,102.96,0.0,unknown,unknown
3248539,3248930,2.0,2019-02-13 17:00:04,2019-02-13 17:00:15,1.0,0.33,5.0,N,1,1,...,116.00,0.0,0.0,23.26,0.0,0.3,139.56,0.0,unknown,unknown
3251639,3252032,1.0,2019-02-13 17:25:13,2019-02-13 17:25:34,1.0,1.60,5.0,N,1,1,...,95.00,0.0,0.0,15.00,0.0,0.3,110.30,0.0,unknown,unknown
3251745,3252138,2.0,2019-02-13 17:04:49,2019-02-13 17:04:56,1.0,0.00,3.0,N,1,1,...,20.00,1.0,0.0,4.26,0.0,0.3,25.56,0.0,unknown,unknown
3265223,3265616,2.0,2019-02-13 18:46:03,2019-02-13 18:46:50,1.0,0.00,5.0,N,1,1,...,120.00,0.0,0.0,10.00,0.0,0.3,130.30,0.0,unknown,unknown
3284705,3285099,1.0,2019-02-13 19:16:51,2019-02-13 19:18:14,1.0,16.50,5.0,N,1,1,...,87.00,0.0,0.0,0.00,0.0,0.3,87.30,0.0,unknown,unknown
3313337,3313731,1.0,2019-02-13 21:10:39,2019-02-13 21:12:46,1.0,4.30,1.0,N,1,1,...,3.00,0.5,0.5,60.00,10.5,0.3,74.80,0.0,unknown,unknown
3357196,3357590,2.0,2019-02-14 02:26:21,2019-02-14 02:26:24,1.0,0.00,5.0,N,1,1,...,25.00,0.0,0.0,3.00,0.0,0.3,28.30,0.0,unknown,unknown
3361252,3361646,1.0,2019-02-14 04:34:40,2019-02-14 04:34:54,0.0,0.00,5.0,N,1,1,...,70.00,0.0,0.0,5.00,0.0,0.3,75.30,0.0,unknown,unknown
3362567,3362961,1.0,2019-02-14 05:59:12,2019-02-14 05:59:59,2.0,0.00,5.0,N,1,1,...,80.00,0.0,0.0,15.00,20.0,0.3,115.30,0.0,unknown,unknown
3362759,3363153,1.0,2019-02-14 05:58:14,2019-02-14 05:59:33,1.0,0.20,5.0,N,1,1,...,90.00,0.0,0.0,15.00,0.0,0.3,105.30,0.0,unknown,unknown
3363584,3363980,1.0,2019-02-14 05:45:50,2019-02-14 05:46:33,2.0,0.00,5.0,N,1,1,...,70.00,0.0,0.0,10.00,0.0,0.3,80.30,0.0,unknown,unknown
3363587,3363983,1.0,2019-02-14 05:42:43,2019-02-14 05:43:25,0.0,0.00,5.0,N,1,1,...,100.00,0.0,0.0,0.00,0.0,0.3,100.30,0.0,unknown,unknown
3366877,3367273,1.0,2019-02-14 06:46:25,2019-02-14 06:46:54,1.0,0.00,5.0,N,1,1,...,83.50,0.0,0.0,16.75,0.0,0.3,100.55,0.0,unknown,unknown
3443977,3444384,2.0,2019-02-14 12:02:29,2019-02-14 12:02:46,2.0,0.00,5.0,N,1,1,...,85.00,0.0,0.5,0.00,15.0,0.3,100.80,0.0,unknown,unknown
3445649,3446056,2.0,2019-02-14 12:26:23,2019-02-14 12:26:25,1.0,0.06,5.0,N,1,1,...,95.00,0.0,0.0,10.00,0.0,0.3,105.30,0.0,unknown,unknown
3477148,3477561,1.0,2019-02-14 14:55:13,2019-02-14 14:55:42,2.0,0.00,5.0,N,1,1,...,110.00,0.0,0.0,0.00,0.0,0.3,110.30,0.0,unknown,unknown
3503131,3503553,1.0,2019-02-14 16:57:27,2019-02-14 16:57:56,1.0,0.00,5.0,N,1,1,...,85.00,0.0,0.0,17.05,0.0,0.3,102.35,0.0,unknown,unknown
3550644,3551071,2.0,2019-02-14 19:56:38,2019-02-14 19:57:38,2.0,0.00,5.0,N,1,1,...,88.00,0.0,0.5,31.83,17.3,0.3,137.93,0.0,unknown,unknown
3566106,3566533,1.0,2019-02-14 20:20:59,2019-02-14 20:21:32,1.0,20.60,5.0,N,1,1,...,120.00,0.0,0.0,15.00,0.0,0.3,135.30,0.0,unknown,unknown

In [9]:
zone_zone_drop=pd.concat([all_1['zone'],all_1['zone_drop']],axis=1)
sdgihlaskdoiyrhoi=zone_zone_drop.pivot_table(values='zone_drop', index="zone", columns='zone_drop',
           fill_value=0, aggfunc=len)
sdgihlaskdoiyrhoi.to_csv('yellowOD.csv')

In [1]:
all_1.to_csv('all1.csv')

NameError: name 'all_1' is not defined

In [3]:
data = pd.read_csv('all1.csv', parse_dates= ['tpep_pickup_datetime','tpep_dropoff_datetime'])
data['pickup_datetime_by_hour']=data['tpep_pickup_datetime'].dt.hour
data['pickup_datetime_by_day']=data['tpep_pickup_datetime'].dt.day
data

,Unnamed: 0,Unnamed: 0.1,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,...,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,zone,zone_drop,pickup_datetime_by_hour,pickup_datetime_by_day
0,381889,382200,2.0,2019-02-02 11:06:00,2019-02-02 11:09:11,3.0,0.00,1.0,N,11,...,0.5,0.00,0.0,0.3,3.30,0.0,brooklyn_1,brooklyn_1,11,2
1,471552,471863,1.0,2019-02-02 17:19:00,2019-02-02 17:19:09,1.0,0.00,1.0,N,11,...,0.5,0.00,0.0,0.3,3.30,0.0,brooklyn_1,brooklyn_1,17,2
2,606107,606421,1.0,2019-02-03 05:12:47,2019-02-03 05:13:09,1.0,0.00,5.0,N,11,...,0.0,0.00,0.0,0.3,55.30,0.0,brooklyn_1,brooklyn_1,5,3
3,684292,684606,1.0,2019-02-03 15:46:49,2019-02-03 15:48:03,1.0,0.00,5.0,N,11,...,0.0,9.45,0.0,0.3,56.75,0.0,brooklyn_1,brooklyn_1,15,3
4,706153,706467,2.0,2019-02-03 16:42:40,2019-02-03 16:56:10,1.0,1.89,1.0,N,11,...,0.5,0.00,0.0,0.3,11.30,0.0,brooklyn_1,brooklyn_1,16,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3618800,3445649,3446056,2.0,2019-02-14 12:26:23,2019-02-14 12:26:25,1.0,0.06,5.0,N,1,...,0.0,10.00,0.0,0.3,105.30,0.0,unknown,unknown,12,14
3618801,3477148,3477561,1.0,2019-02-14 14:55:13,2019-02-14 14:55:42,2.0,0.00,5.0,N,1,...,0.0,0.00,0.0,0.3,110.30,0.0,unknown,unknown,14,14
3618802,3503131,3503553,1.0,2019-02-14 16:57:27,2019-02-14 16:57:56,1.0,0.00,5.0,N,1,...,0.0,17.05,0.0,0.3,102.35,0.0,unknown,unknown,16,14
3618803,3550644,3551071,2.0,2019-02-14 19:56:38,2019-02-14 19:57:38,2.0,0.00,5.0,N,1,...,0.5,31.83,17.3,0.3,137.93,0.0,unknown,unknown,19,14
3618804,3566106,3566533,1.0,2019-02-14 20:20:59,2019-02-14 20:21:32,1.0,20.60,5.0,N,1,...,0.0,15.00,0.0,0.3,135.30,0.0,unknown,unknown,20,14

In [29]:
data

MemoryError: Unable to allocate 82.8 MiB for an array with shape (3, 3618805) and data type float64

MemoryError: Unable to allocate 82.8 MiB for an array with shape (3, 3618805) and data type int64